### ISSUE TITLE
sysinfo fails while pulling get_login_info

### ISSUE THREAD

**Issue by bortok** [OpenIxia/ixvision-zta#12]
Platform AS5812, version "trunk-213356-20190130-131158"

(ixvision) ubuntu@ixvzta:~/ixvision$ "$PYENV_DIR/ixvision-zta/ixvztp" -u $WEB_API_USERNAME -p $WEB_API_PASSWORD -d $DEVICE_IP sysinfo
Starting system information inquiry for 172.20.100.32
Traceback (most recent call last):
  File "/home/ubuntu/ixvision/ixvision-zta/ixvztp", line 113, in <module>
    nto_get_sysinfo(host, port, username, password)
  File "/home/ubuntu/ixvision/ixvision-zta/ixvision_ztp_sysinfo.py", line 37, in nto_get_sysinfo
    nto_hardware_info = nto.getLoginInfo()['hardware_info']
  File "/home/ubuntu/ixvision/ixvision-zta/ixia_nto.py", line 324, in getLoginInfo
    return self._callServer('POST', '/api/actions/get_login_info', None)
  File "/home/ubuntu/ixvision/ixvision-zta/ixia_nto.py", line 97, in _callServer
    data = json.loads(data.decode('ascii'))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Debug

Sending a message to the server with parameters:
 HTTPMethod=POST
 URL=/api/actions/get_login_info
 argsAPI=None
Response:
 Status=400
 Reason=Bad Request
 Headers=HTTPHeaderDict({'Content-Length': '76', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self' 'unsafe-eval' 'unsafe-inline'; frame-ancestors 'self'; img-src http: https: data:", 'Accept-Ranges': 'bytes', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Server': 'Restlet-Framework/2.3.7', 'Pragma': 'no-cache', 'Cache-Control': 's-maxage=100, must-revalidate, no-cache, no-store, no-transform, private', 'Date': 'Tue, 12 Feb 2019 16:10:14 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Type': 'text/plain; charset=UTF-8', 'Public-Key-Pins': 'pin-sha256="91eaiBlpaQ2uZ95MhUIbgk5bNM5sh+hDN9mNa/2+704="; max-age=5184000; includeSubDomains'})
 Data=org.json.JSONException: A JSONObject text must begin with '{' at character 1
 decode=True

**Comment by bortok** [comment]
Confirmed this is Vision OS version related, since sysinfo action works with 4.7.6.9 (E10S)

**Comment by bortok** [comment]
Also confirmed working on 4.8.0.22 (E10S)

**Comment by bortok** [comment]
Service request 837677 to fix /api/actions/get_login_info on API side

**Comment by bortok** [comment]
Double-checked on different versions and platforms. The issue is NOT version or platform related. The same device request produces the error when queried from newly deployed ubuntu host with ixvision-zta installed from github. At the same time it works from development environment, on the same code version. Looking into dependencies

**Comment by bortok** [comment]
There is a bug in ixia_nto.py implementation, fixed in the fork https://github.com/bortok/VisionNPB. To be incorporated back into original https://github.com/OpenIxia/VisionNPB

**Comment by bortok** [comment]
The issue has been addressed in openixia/VisionNPB@e4a4bfa
